export const airbnbLocations = [
  {
    label: 'Argentina',
    value: 'argentina',
    cities: [
      { label: 'Bariloche', value: 'bariloche' },
      { label: 'Buenos Aires', value: 'buenos aires' },
      { label: 'Cordoba', value: 'cordoba' },
      { label: 'Mendoza', value: 'mendoza' },
      { label: 'Rosario', value: 'rosario' },
    ],
  },
  {
    label: 'Australia',
    value: 'australia',
    cities: [
      { label: 'Adelaide', value: 'adelaide' },
      { label: 'Brisbane', value: 'brisbane' },
      { label: 'Melbourne', value: 'melbourne' },
      { label: 'Perth', value: 'perth' },
      { label: 'Sydney', value: 'sydney' },
    ],
  },
  {
    label: 'Austria',
    value: 'austria',
    cities: [
      { label: 'Graz', value: 'graz' },
      { label: 'Innsbruck', value: 'innsbruck' },
      { label: 'Linz', value: 'linz' },
      { label: 'Salzburg', value: 'salzburg' },
      { label: 'Vienna', value: 'vienna' },
    ],
  },
  {
    label: 'Belgium',
    value: 'belgium',
    cities: [
      { label: 'Antwerp', value: 'antwerp' },
      { label: 'Bruges', value: 'bruges' },
      { label: 'Brussels', value: 'brussels' },
      { label: 'Ghent', value: 'ghent' },
      { label: 'Liège', value: 'liege' },
    ],
  },
  {
    label: 'Brazil',
    value: 'brazil',
    cities: [
      { label: 'Florianópolis', value: 'florianopolis' },
      { label: 'Fortaleza', value: 'fortaleza' },
      { label: 'Rio de Janeiro', value: 'rio de janeiro' },
      { label: 'Salvador', value: 'salvador' },
      { label: 'São Paulo', value: 'sao paulo' },
    ],
  },
  {
    label: 'Bulgaria',
    value: 'bulgaria',
    cities: [
      { label: 'Burgas', value: 'burgas' },
      { label: 'Plovdiv', value: 'plovdiv' },
      { label: 'Sofia', value: 'sofia' },
      { label: 'Varna', value: 'varna' },
      { label: 'Veliko Tarnovo', value: 'veliko tarnovo' },
    ],
  },
  {
    label: 'Cambodia',
    value: 'cambodia',
    cities: [
      { label: 'Battambang', value: 'battambang' },
      { label: 'Kampot', value: 'kampot' },
      { label: 'Phnom Penh', value: 'phnom penh' },
      { label: 'Siem Reap', value: 'siem reap' },
      { label: 'Sihanoukville', value: 'sihanoukville' },
    ],
  },
  {
    label: 'Canada',
    value: 'canada',
    cities: [
      { label: 'Calgary', value: 'calgary' },
      { label: 'Montreal', value: 'montreal' },
      { label: 'Ottawa', value: 'ottawa' },
      { label: 'Toronto', value: 'toronto' },
      { label: 'Vancouver', value: 'vancouver' },
    ],
  },
  {
    label: 'Chile',
    value: 'chile',
    cities: [
      { label: 'Pucón', value: 'pucon' },
      { label: 'Puerto Varas', value: 'puerto varas' },
      { label: 'Santiago', value: 'santiago' },
      { label: 'Valparaiso', value: 'valparaiso' },
      { label: 'Viña del Mar', value: 'vina del mar' },
    ],
  },
  {
    label: 'China',
    value: 'china',
    cities: [
      { label: 'Beijing', value: 'beijing' },
      { label: 'Chengdu', value: 'chengdu' },
      { label: 'Guangzhou', value: 'guangzhou' },
      { label: 'Shanghai', value: 'shanghai' },
      { label: 'Shenzhen', value: 'shenzhen' },
    ],
  },
  {
    label: 'Colombia',
    value: 'colombia',
    cities: [
      { label: 'Bogotá', value: 'bogota' },
      { label: 'Cali', value: 'cali' },
      { label: 'Cartagena', value: 'cartagena' },
      { label: 'Medellín', value: 'medellin' },
      { label: 'Santa Marta', value: 'santa marta' },
    ],
  },
  {
    label: 'Costa Rica',
    value: 'costa rica',
    cities: [
      { label: 'Jaco', value: 'jaco' },
      { label: 'Manuel Antonio', value: 'manuel antonio' },
      { label: 'San Jose', value: 'san jose' },
      { label: 'Tamarindo', value: 'tamarindo' },
      { label: 'Uvita', value: 'uvita' },
    ],
  },
  {
    label: 'Croatia',
    value: 'croatia',
    cities: [
      { label: 'Dubrovnik', value: 'dubrovnik' },
      { label: 'Hvar', value: 'hvar' },
      { label: 'Split', value: 'split' },
      { label: 'Zadar', value: 'zadar' },
      { label: 'Zagreb', value: 'zagreb' },
    ],
  },
  {
    label: 'Czech Republic',
    value: 'czech republic',
    cities: [
      { label: 'Brno', value: 'brno' },
      { label: 'Olomouc', value: 'olomouc' },
      { label: 'Ostrava', value: 'ostrava' },
      { label: 'Pilsen', value: 'pilsen' },
      { label: 'Prague', value: 'prague' },
    ],
  },
  {
    label: 'Denmark',
    value: 'denmark',
    cities: [
      { label: 'Aalborg', value: 'aalborg' },
      { label: 'Aarhus', value: 'aarhus' },
      { label: 'Copenhagen', value: 'copenhagen' },
      { label: 'Helsingor', value: 'helsingor' },
      { label: 'Odense', value: 'odense' },
    ],
  },
  {
    label: 'Ecuador',
    value: 'ecuador',
    cities: [
      { label: 'Baños', value: 'banos' },
      { label: 'Cuenca', value: 'cuenca' },
      { label: 'Guayaquil', value: 'guayaquil' },
      { label: 'Montañita', value: 'montanita' },
      { label: 'Quito', value: 'quito' },
    ],
  },
  {
    label: 'Finland',
    value: 'finland',
    cities: [
      { label: 'Helsinki', value: 'helsinki' },
      { label: 'Oulu', value: 'oulu' },
      { label: 'Rovaniemi', value: 'rovaniemi' },
      { label: 'Tampere', value: 'tampere' },
      { label: 'Turku', value: 'turku' },
    ],
  },
  {
    label: 'France',
    value: 'france',
    cities: [
      { label: 'Bordeaux', value: 'bordeaux' },
      { label: 'Lyon', value: 'lyon' },
      { label: 'Marseille', value: 'marseille' },
      { label: 'Nice', value: 'nice' },
      { label: 'Paris', value: 'paris' },
    ],
  },
  {
    label: 'Germany',
    value: 'germany',
    cities: [
      { label: 'Berlin', value: 'berlin' },
      { label: 'Cologne', value: 'cologne' },
      { label: 'Frankfurt', value: 'frankfurt' },
      { label: 'Hamburg', value: 'hamburg' },
      { label: 'Munich', value: 'munich' },
    ],
  },
  {
    label: 'Greece',
    value: 'greece',
    cities: [
      { label: 'Athens', value: 'athens' },
      { label: 'Crete', value: 'crete' },
      { label: 'Mykonos', value: 'mykonos' },
      { label: 'Santorini', value: 'santorini' },
      { label: 'Thessaloniki', value: 'thessaloniki' },
    ],
  },
  {
    label: 'Hong Kong',
    value: 'hong kong',
    cities: [
      { label: 'Hong Kong Island', value: 'hong kong island' },
      { label: 'Kowloon', value: 'kowloon' },
      { label: 'New Territories', value: 'new territories' },
    ],
  },
  {
    label: 'Hungary',
    value: 'hungary',
    cities: [
      { label: 'Budapest', value: 'budapest' },
      { label: 'Debrecen', value: 'debrecen' },
      { label: 'Miskolc', value: 'miskolc' },
      { label: 'Pecs', value: 'pecs' },
      { label: 'Szeged', value: 'szeged' },
    ],
  },
  {
    label: 'Iceland',
    value: 'iceland',
    cities: [
      { label: 'Akureyri', value: 'akureyri' },
      { label: 'Egilsstadir', value: 'egilsstadir' },
      { label: 'Hofn', value: 'hofn' },
      { label: 'Reykjavik', value: 'reykjavik' },
      { label: 'Vik', value: 'vik' },
    ],
  },
  {
    label: 'India',
    value: 'india',
    cities: [
      { label: 'Bangalore', value: 'bangalore' },
      { label: 'Goa', value: 'goa' },
      { label: 'Jaipur', value: 'jaipur' },
      { label: 'Mumbai', value: 'mumbai' },
      { label: 'New Delhi', value: 'new delhi' },
    ],
  },
  {
    label: 'Indonesia',
    value: 'indonesia',
    cities: [
      { label: 'Bali', value: 'bali' },
      { label: 'Bandung', value: 'bandung' },
      { label: 'Jakarta', value: 'jakarta' },
      { label: 'Surabaya', value: 'surabaya' },
      { label: 'Yogyakarta', value: 'yogyakarta' },
    ],
  },
  {
    label: 'Ireland',
    value: 'ireland',
    cities: [
      { label: 'Cork', value: 'cork' },
      { label: 'Dublin', value: 'dublin' },
      { label: 'Galway', value: 'galway' },
      { label: 'Killarney', value: 'killarney' },
      { label: 'Limerick', value: 'limerick' },
    ],
  },
  {
    label: 'Israel',
    value: 'israel',
    cities: [
      { label: 'Eilat', value: 'eilat' },
      { label: 'Haifa', value: 'haifa' },
      { label: 'Jerusalem', value: 'jerusalem' },
      { label: 'Nazareth', value: 'nazareth' },
      { label: 'Tel Aviv', value: 'tel aviv' },
    ],
  },
  {
    label: 'Italy',
    value: 'italy',
    cities: [
      { label: 'Florence', value: 'florence' },
      { label: 'Milan', value: 'milan' },
      { label: 'Naples', value: 'naples' },
      { label: 'Rome', value: 'rome' },
      { label: 'Venice', value: 'venice' },
    ],
  },
  {
    label: 'Japan',
    value: 'japan',
    cities: [
      { label: 'Fukuoka', value: 'fukuoka' },
      { label: 'Kyoto', value: 'kyoto' },
      { label: 'Osaka', value: 'osaka' },
      { label: 'Sapporo', value: 'sapporo' },
      { label: 'Tokyo', value: 'tokyo' },
    ],
  },
  {
    label: 'Kenya',
    value: 'kenya',
    cities: [
      { label: 'Eldoret', value: 'eldoret' },
      { label: 'Kisumu', value: 'kisumu' },
      { label: 'Mombasa', value: 'mombasa' },
      { label: 'Nairobi', value: 'nairobi' },
      { label: 'Nakuru', value: 'nakuru' },
    ],
  },
  {
    label: 'Malaysia',
    value: 'malaysia',
    cities: [
      { label: 'Johor Bahru', value: 'johor bahru' },
      { label: 'Kuala Lumpur', value: 'kuala lumpur' },
      { label: 'Langkawi', value: 'langkawi' },
      { label: 'Malacca', value: 'malacca' },
      { label: 'Penang', value: 'penang' },
    ],
  },
  {
    label: 'Mexico',
    value: 'mexico',
    cities: [
      { label: 'Cabo San Lucas', value: 'cabo san lucas' },
      { label: 'Cancun', value: 'cancun' },
      { label: 'Mexico City', value: 'mexico city' },
      { label: 'Playa del Carmen', value: 'playa del carmen' },
      { label: 'Puerto Vallarta', value: 'puerto vallarta' },
    ],
  },
  {
    label: 'Morocco',
    value: 'morocco',
    cities: [
      { label: 'Casablanca', value: 'casablanca' },
      { label: 'Fes', value: 'fes' },
      { label: 'Marrakech', value: 'marrakech' },
      { label: 'Rabat', value: 'rabat' },
      { label: 'Tangier', value: 'tangier' },
    ],
  },
  {
    label: 'Netherlands',
    value: 'netherlands',
    cities: [
      { label: 'Amsterdam', value: 'amsterdam' },
      { label: 'Eindhoven', value: 'eindhoven' },
      { label: 'Rotterdam', value: 'rotterdam' },
      { label: 'The Hague', value: 'the hague' },
      { label: 'Utrecht', value: 'utrecht' },
    ],
  },
  {
    label: 'New Zealand',
    value: 'new zealand',
    cities: [
      { label: 'Auckland', value: 'auckland' },
      { label: 'Christchurch', value: 'christchurch' },
      { label: 'Queenstown', value: 'queenstown' },
      { label: 'Rotorua', value: 'rotorua' },
      { label: 'Wellington', value: 'wellington' },
    ],
  },
  {
    label: 'Norway',
    value: 'norway',
    cities: [
      { label: 'Bergen', value: 'bergen' },
      { label: 'Oslo', value: 'oslo' },
      { label: 'Stavanger', value: 'stavanger' },
      { label: 'Tromso', value: 'tromso' },
      { label: 'Trondheim', value: 'trondheim' },
    ],
  },
  {
    label: 'Peru',
    value: 'peru',
    cities: [
      { label: 'Arequipa', value: 'arequipa' },
      { label: 'Cusco', value: 'cusco' },
      { label: 'Iquitos', value: 'iquitos' },
      { label: 'Lima', value: 'lima' },
      { label: 'Trujillo', value: 'trujillo' },
    ],
  },
  {
    label: 'Philippines',
    value: 'philippines',
    cities: [
      { label: 'Boracay', value: 'boracay' },
      { label: 'Cebu', value: 'cebu' },
      { label: 'Manila', value: 'manila' },
      { label: 'Palawan', value: 'palawan' },
      { label: 'Siargao', value: 'siargao' },
    ],
  },
  {
    label: 'Poland',
    value: 'poland',
    cities: [
      { label: 'Gdansk', value: 'gdansk' },
      { label: 'Krakow', value: 'krakow' },
      { label: 'Poznan', value: 'poznan' },
      { label: 'Warsaw', value: 'warsaw' },
      { label: 'Wroclaw', value: 'wroclaw' },
    ],
  },
  {
    label: 'Portugal',
    value: 'portugal',
    cities: [
      { label: 'Algarve', value: 'algarve' },
      { label: 'Coimbra', value: 'coimbra' },
      { label: 'Lisbon', value: 'lisbon' },
      { label: 'Madeira', value: 'madeira' },
      { label: 'Porto', value: 'porto' },
    ],
  },
  {
    label: 'Romania',
    value: 'romania',
    cities: [
      { label: 'Brasov', value: 'brasov' },
      { label: 'Bucharest', value: 'bucharest' },
      { label: 'Cluj-Napoca', value: 'cluj-napoca' },
      { label: 'Iasi', value: 'iasi' },
      { label: 'Timisoara', value: 'timisoara' },
    ],
  },
  {
    label: 'Russia',
    value: 'russia',
    cities: [
      { label: 'Kazan', value: 'kazan' },
      { label: 'Moscow', value: 'moscow' },
      { label: 'Sochi', value: 'sochi' },
      { label: 'St. Petersburg', value: 'st petersburg' },
      { label: 'Yekaterinburg', value: 'yekaterinburg' },
    ],
  },
  {
    label: 'Singapore',
    value: 'singapore',
    cities: [{ label: 'Singapore', value: 'singapore' }],
  },
  {
    label: 'South Africa',
    value: 'south africa',
    cities: [
      { label: 'Cape Town', value: 'cape town' },
      { label: 'Durban', value: 'durban' },
      { label: 'Johannesburg', value: 'johannesburg' },
      { label: 'Port Elizabeth', value: 'port elizabeth' },
      { label: 'Pretoria', value: 'pretoria' },
    ],
  },
  {
    label: 'South Korea',
    value: 'south korea',
    cities: [
      { label: 'Busan', value: 'busan' },
      { label: 'Daegu', value: 'daegu' },
      { label: 'Incheon', value: 'incheon' },
      { label: 'Jeju Island', value: 'jeju island' },
      { label: 'Seoul', value: 'seoul' },
    ],
  },
  {
    label: 'Spain',
    value: 'spain',
    cities: [
      { label: 'Barcelona', value: 'barcelona' },
      { label: 'Madrid', value: 'madrid' },
      { label: 'Malaga', value: 'malaga' },
      { label: 'Seville', value: 'seville' },
      { label: 'Valencia', value: 'valencia' },
    ],
  },
  {
    label: 'Sri Lanka',
    value: 'sri lanka',
    cities: [
      { label: 'Colombo', value: 'colombo' },
      { label: 'Galle', value: 'galle' },
      { label: 'Kandy', value: 'kandy' },
      { label: 'Nuwara Eliya', value: 'nuwara eliya' },
      { label: 'Sigiriya', value: 'sigiriya' },
    ],
  },
  {
    label: 'Sweden',
    value: 'sweden',
    cities: [
      { label: 'Gothenburg', value: 'gothenburg' },
      { label: 'Helsingborg', value: 'helsingborg' },
      { label: 'Malmo', value: 'malmo' },
      { label: 'Stockholm', value: 'stockholm' },
      { label: 'Uppsala', value: 'uppsala' },
    ],
  },
  {
    label: 'Switzerland',
    value: 'switzerland',
    cities: [
      { label: 'Basel', value: 'basel' },
      { label: 'Bern', value: 'bern' },
      { label: 'Geneva', value: 'geneva' },
      { label: 'Lucerne', value: 'lucerne' },
      { label: 'Zurich', value: 'zurich' },
    ],
  },
  {
    label: 'Taiwan',
    value: 'taiwan',
    cities: [
      { label: 'Hualien', value: 'hualien' },
      { label: 'Kaohsiung', value: 'kaohsiung' },
      { label: 'Taichung', value: 'taichung' },
      { label: 'Tainan', value: 'tainan' },
      { label: 'Taipei', value: 'taipei' },
    ],
  },
  {
    label: 'Thailand',
    value: 'thailand',
    cities: [
      { label: 'Bangkok', value: 'bangkok' },
      { label: 'Chiang Mai', value: 'chiang mai' },
      { label: 'Koh Samui', value: 'koh samui' },
      { label: 'Krabi', value: 'krabi' },
      { label: 'Phuket', value: 'phuket' },
    ],
  },
  {
    label: 'Turkey',
    value: 'turkey',
    cities: [
      { label: 'Ankara', value: 'ankara' },
      { label: 'Antalya', value: 'antalya' },
      { label: 'Cappadocia', value: 'cappadocia' },
      { label: 'Istanbul', value: 'istanbul' },
      { label: 'Izmir', value: 'izmir' },
    ],
  },
  {
    label: 'Ukraine',
    value: 'ukraine',
    cities: [
      { label: 'Dnipro', value: 'dnipro' },
      { label: 'Kharkiv', value: 'kharkiv' },
      { label: 'Kyiv', value: 'kyiv' },
      { label: 'Lviv', value: 'lviv' },
      { label: 'Odesa', value: 'odesa' },
    ],
  },
  {
    label: 'United Arab Emirates',
    value: 'united arab emirates',
    cities: [
      { label: 'Abu Dhabi', value: 'abu dhabi' },
      { label: 'Ajman', value: 'ajman' },
      { label: 'Dubai', value: 'dubai' },
      { label: 'Ras Al Khaimah', value: 'ras al khaimah' },
      { label: 'Sharjah', value: 'sharjah' },
    ],
  },
  {
    label: 'United Kingdom',
    value: 'united kingdom',
    cities: [
      { label: 'Edinburgh', value: 'edinburgh' },
      { label: 'Glasgow', value: 'glasgow' },
      { label: 'Liverpool', value: 'liverpool' },
      { label: 'London', value: 'london' },
      { label: 'Manchester', value: 'manchester' },
    ],
  },
  {
    label: 'United States',
    value: 'united states',
    cities: [
      { label: 'Boston', value: 'boston' },
      { label: 'Chicago', value: 'chicago' },
      { label: 'Las Vegas', value: 'las vegas' },
      { label: 'Los Angeles', value: 'los angeles' },
      { label: 'Miami', value: 'miami' },
      { label: 'New York', value: 'new york' },
      { label: 'Orlando', value: 'orlando' },
      { label: 'San Francisco', value: 'san francisco' },
      { label: 'Seattle', value: 'seattle' },
      { label: 'Washington D.C.', value: 'washington dc' },
    ],
  },
  {
    label: 'Uruguay',
    value: 'uruguay',
    cities: [
      { label: 'Colonia del Sacramento', value: 'colonia del sacramento' },
      { label: 'Montevideo', value: 'montevideo' },
      { label: 'Punta del Este', value: 'punta del este' },
    ],
  },
  {
    label: 'Vietnam',
    value: 'vietnam',
    cities: [
      { label: 'Da Nang', value: 'da nang' },
      { label: 'Hanoi', value: 'hanoi' },
      { label: 'Ho Chi Minh City', value: 'ho chi minh city' },
      { label: 'Hoi An', value: 'hoi an' },
      { label: 'Nha Trang', value: 'nha trang' },
    ],
  },
];
